config/routes.rb
RorBugtracker::Application.routes.draw do
  get "versions/create"

  get "components/create"

  get "home/index"

  resources :home, :only => :index

  devise_for :users

  match 'projects/:id/settings', :to => 'projects#settings', :via => :get
  resources :projects do
    get :autocomplete_user_email, :on => :collection
  end

  resources :users, :only => :show

  resources :user_projects
  match 'user_projects/delete/:uid/:pid', :to => 'user_projects#delete', :via => :delete

  resources :issues
  match 'projects/:id/issues', :to => 'issues#of_project', :via => :get
  match 'projects/:id/issues/new', :to => 'issues#new', :via => :get
  match 'issues/add_like/:id', :to => 'issues#add_like', :via => :get

  resources :histories

  resource :components
  match 'components/create', :to => 'components#create', :via => :post
  match 'components/delete/:id', :to => 'components#delete', :via => :get

  resource :versions
  match 'versions/create', :to => 'versions#create', :via => :post
  match 'versions/delete/:id', :to => 'versions#delete', :via => :get

  resource :comments
  match 'versions/create', :to => 'versions#create', :via => :post
  match 'comments/delete/:id', :to => 'comments#delete', :via => :get

  post 'issues/apply_filters'

  root :to => 'home#index'

end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  attr_accessible :role
  enum_attr :role, %w(^manager assignee)

  belongs_to :user
  belongs_to :project

  before_validation do |user_project|
    user_project.role = :manager
  end
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  def create
    @project = Project.find(params[:user_projects][:project_id])
    @up = @project.user_projects.new()
    if  (User.where(:email => params[:user_projects][:email]).exists?)
      @up.user = User.find_by_email(params[:user_projects][:email])
      if !(UserProject.where(:user_id => @up.user.id, :project_id => @up.project.id).exists?)
        @up.save!
        @up.update_column(:role, params[:user_projects][:role])
        respond_to do |format|
          format.json { render :json => @up }
          format.js #added
        end
      end
    end
  end

  def delete
    #if Project.find(params[:pid]).author.id == params[:uid]
    #  return
    #end
    @up = UserProject.where(:user_id => params[:uid], :project_id => params[:pid]).first
    @up.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js #added
    end
  end
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/user_projects/_form.html.erb
<%= form_for :user_projects, :remote => true, :url => {:controller => :user_projects, :action => :create} do |f| %>
    <p>
      <%= f.label :user_email %><br />
      <%= f.autocomplete_field :email, autocomplete_user_email_projects_path, :id_element => '#auto_email'%>
    </p>
    <p>
      Manager <%= f.radio_button :role, :manager %>
      Developer <%= f.radio_button :role, :assignee %>
    </p>
    <%= f.hidden_field :project_id, :value => @project.id %>
    <p>
      <%= f.submit 'Add member', :class => 'btn btn-inverse'%>
    </p>
<% end %>

app/views/user_projects/create.js.erb
$('#members').append('<%= escape_javascript(render(:template => "projects/_edit_user", :locals => {:edit_user => @up.user, :project => @project})) %>');
$('#member_form > form')[0].reset();

app/views/user_projects/delete.js.erb
$("#u<%= @up.id%>").remove();