config/routes.rb
RorBugtracker::Application.routes.draw do
  get "versions/create"

  get "components/create"

  get "home/index"

  resources :home, :only => :index

  devise_for :users

  match 'projects/:id/settings', :to => 'projects#settings', :via => :get
  resources :projects do
    get :autocomplete_user_email, :on => :collection
  end

  resources :users, :only => :show

  resources :user_projects
  match 'user_projects/delete/:uid/:pid', :to => 'user_projects#delete', :via => :delete

  resources :issues
  match 'projects/:id/issues', :to => 'issues#of_project', :via => :get
  match 'projects/:id/issues/new', :to => 'issues#new', :via => :get
  match 'issues/add_like/:id', :to => 'issues#add_like', :via => :get

  resources :histories

  resource :components
  match 'components/create', :to => 'components#create', :via => :post
  match 'components/delete/:id', :to => 'components#delete', :via => :get

  resource :versions
  match 'versions/create', :to => 'versions#create', :via => :post
  match 'versions/delete/:id', :to => 'versions#delete', :via => :get

  resource :comments
  match 'versions/create', :to => 'versions#create', :via => :post
  match 'comments/delete/:id', :to => 'comments#delete', :via => :get

  post 'issues/apply_filters'

  root :to => 'home#index'

end

app/views/layouts/_navigation.html.erb
<%= link_to "Bugtracker", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
      <li>
        <%= link_to 'My projects', projects_url %>
      </li>
      <li>
        <%= link_to 'New project', new_project_url %>
      </li>
      <li>
        <%= link_to current_user.login, user_url(current_user) %>
      </li>
      <li>
        <%= image_tag current_user.avatar.url(:small) %>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
          </li>
          <li>
            <%= link_to('Edit account', edit_user_registration_path) %>
          </li>
        </ul>
      </li>
  <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>
      </li>
      <li>
        <%= link_to('Sign up', new_user_registration_path)  %>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorBugtracker</title>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= yield(:head) %><meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults%>
  <%= javascript_include_tag "autocomplete-rails.js"%>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>

</head>
<body>
<header class="navbar">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>

<%= yield %>

</body>
</html>